use std::collections::HashMap;

pub fn countries() -> HashMap<String, String> {
    HashMap::from([
        ("AF".to_string(), "Afghanistan".to_string()),
        ("AL".to_string(), "Albania".to_string()),
        ("DZ".to_string(), "Algeria".to_string()),
        ("AS".to_string(), "American Samoa".to_string()),
        ("AD".to_string(), "Andorra".to_string()),
        ("AO".to_string(), "Angola".to_string()),
        ("AI".to_string(), "Anguilla".to_string()),
        ("AQ".to_string(), "Antarctica".to_string()),
        ("AG".to_string(), "Antigua and Barbuda".to_string()),
        ("AR".to_string(), "Argentina".to_string()),
        ("AM".to_string(), "Armenia".to_string()),
        ("AW".to_string(), "Aruba".to_string()),
        ("AU".to_string(), "Australia".to_string()),
        ("AT".to_string(), "Austria".to_string()),
        ("AZ".to_string(), "Azerbaijan".to_string()),
        ("BS".to_string(), "Bahamas".to_string()),
        ("BH".to_string(), "Bahrain".to_string()),
        ("BD".to_string(), "Bangladesh".to_string()),
        ("BB".to_string(), "Barbados".to_string()),
        ("BY".to_string(), "Belarus".to_string()),
        ("BE".to_string(), "Belgium".to_string()),
        ("BZ".to_string(), "Belize".to_string()),
        ("BJ".to_string(), "Benin".to_string()),
        ("BM".to_string(), "Bermuda".to_string()),
        ("BT".to_string(), "Bhutan".to_string()),
        ("BO".to_string(), "Bolivia".to_string()),
        ("BA".to_string(), "Bosnia and Herzegovina".to_string()),
        ("BW".to_string(), "Botswana".to_string()),
        ("BR".to_string(), "Brazil".to_string()),
        (
            "IO".to_string(),
            "British Indian Ocean Territory".to_string(),
        ),
        ("VG".to_string(), "British Virgin Islands".to_string()),
        ("BN".to_string(), "Brunei".to_string()),
        ("BG".to_string(), "Bulgaria".to_string()),
        ("BF".to_string(), "Burkina Faso".to_string()),
        ("BI".to_string(), "Burundi".to_string()),
        ("KH".to_string(), "Cambodia".to_string()),
        ("CM".to_string(), "Cameroon".to_string()),
        ("CA".to_string(), "Canada".to_string()),
        ("CV".to_string(), "Cape Verde".to_string()),
        ("KY".to_string(), "Cayman Islands".to_string()),
        ("CF".to_string(), "Central African Republic".to_string()),
        ("TD".to_string(), "Chad".to_string()),
        ("CL".to_string(), "Chile".to_string()),
        ("CN".to_string(), "China".to_string()),
        ("CX".to_string(), "Christmas Island".to_string()),
        ("CC".to_string(), "Cocos Islands".to_string()),
        ("CO".to_string(), "Colombia".to_string()),
        ("KM".to_string(), "Comoros".to_string()),
        ("CK".to_string(), "Cook Islands".to_string()),
        ("CR".to_string(), "Costa Rica".to_string()),
        ("HR".to_string(), "Croatia".to_string()),
        ("CU".to_string(), "Cuba".to_string()),
        ("CW".to_string(), "Curacao".to_string()),
        ("CY".to_string(), "Cyprus".to_string()),
        ("CZ".to_string(), "Czech Republic".to_string()),
        (
            "CD".to_string(),
            "Democratic Republic of the Congo".to_string(),
        ),
        ("DK".to_string(), "Denmark".to_string()),
        ("DJ".to_string(), "Djibouti".to_string()),
        ("DM".to_string(), "Dominica".to_string()),
        ("DO".to_string(), "Dominican Republic".to_string()),
        ("TL".to_string(), "East Timor".to_string()),
        ("EC".to_string(), "Ecuador".to_string()),
        ("EG".to_string(), "Egypt".to_string()),
        ("SV".to_string(), "El Salvador".to_string()),
        ("GQ".to_string(), "Equatorial Guinea".to_string()),
        ("ER".to_string(), "Eritrea".to_string()),
        ("EE".to_string(), "Estonia".to_string()),
        ("ET".to_string(), "Ethiopia".to_string()),
        ("FK".to_string(), "Falkland Islands".to_string()),
        ("FO".to_string(), "Faroe Islands".to_string()),
        ("FJ".to_string(), "Fiji".to_string()),
        ("FI".to_string(), "Finland".to_string()),
        ("FR".to_string(), "France".to_string()),
        ("PF".to_string(), "French Polynesia".to_string()),
        ("GA".to_string(), "Gabon".to_string()),
        ("GM".to_string(), "Gambia".to_string()),
        ("GE".to_string(), "Georgia".to_string()),
        ("DE".to_string(), "Germany".to_string()),
        ("GH".to_string(), "Ghana".to_string()),
        ("GI".to_string(), "Gibraltar".to_string()),
        ("GR".to_string(), "Greece".to_string()),
        ("GL".to_string(), "Greenland".to_string()),
        ("GD".to_string(), "Grenada".to_string()),
        ("GU".to_string(), "Guam".to_string()),
        ("GT".to_string(), "Guatemala".to_string()),
        ("GG".to_string(), "Guernsey".to_string()),
        ("GN".to_string(), "Guinea".to_string()),
        ("GW".to_string(), "Guinea-Bissau".to_string()),
        ("GY".to_string(), "Guyana".to_string()),
        ("HT".to_string(), "Haiti".to_string()),
        ("HN".to_string(), "Honduras".to_string()),
        ("HK".to_string(), "Hong Kong".to_string()),
        ("HU".to_string(), "Hungary".to_string()),
        ("IS".to_string(), "Iceland".to_string()),
        ("IN".to_string(), "India".to_string()),
        ("ID".to_string(), "Indonesia".to_string()),
        ("IR".to_string(), "Iran".to_string()),
        ("IQ".to_string(), "Iraq".to_string()),
        ("IE".to_string(), "Ireland".to_string()),
        ("IM".to_string(), "Isle of Man".to_string()),
        ("IL".to_string(), "Israel".to_string()),
        ("IT".to_string(), "Italy".to_string()),
        ("CI".to_string(), "Ivory Coast".to_string()),
        ("JM".to_string(), "Jamaica".to_string()),
        ("JP".to_string(), "Japan".to_string()),
        ("JE".to_string(), "Jersey".to_string()),
        ("JO".to_string(), "Jordan".to_string()),
        ("KZ".to_string(), "Kazakhstan".to_string()),
        ("KE".to_string(), "Kenya".to_string()),
        ("KI".to_string(), "Kiribati".to_string()),
        ("XK".to_string(), "Kosovo".to_string()),
        ("KW".to_string(), "Kuwait".to_string()),
        ("KG".to_string(), "Kyrgyzstan".to_string()),
        ("LA".to_string(), "Laos".to_string()),
        ("LV".to_string(), "Latvia".to_string()),
        ("LB".to_string(), "Lebanon".to_string()),
        ("LS".to_string(), "Lesotho".to_string()),
        ("LR".to_string(), "Liberia".to_string()),
        ("LY".to_string(), "Libya".to_string()),
        ("LI".to_string(), "Liechtenstein".to_string()),
        ("LT".to_string(), "Lithuania".to_string()),
        ("LU".to_string(), "Luxembourg".to_string()),
        ("MO".to_string(), "Macau".to_string()),
        ("MK".to_string(), "Macedonia".to_string()),
        ("MG".to_string(), "Madagascar".to_string()),
        ("MW".to_string(), "Malawi".to_string()),
        ("MY".to_string(), "Malaysia".to_string()),
        ("MV".to_string(), "Maldives".to_string()),
        ("ML".to_string(), "Mali".to_string()),
        ("MT".to_string(), "Malta".to_string()),
        ("MH".to_string(), "Marshall Islands".to_string()),
        ("MR".to_string(), "Mauritania".to_string()),
        ("MU".to_string(), "Mauritius".to_string()),
        ("YT".to_string(), "Mayotte".to_string()),
        ("MX".to_string(), "Mexico".to_string()),
        ("FM".to_string(), "Micronesia".to_string()),
        ("MD".to_string(), "Moldova".to_string()),
        ("MC".to_string(), "Monaco".to_string()),
        ("MN".to_string(), "Mongolia".to_string()),
        ("ME".to_string(), "Montenegro".to_string()),
        ("MS".to_string(), "Montserrat".to_string()),
        ("MA".to_string(), "Morocco".to_string()),
        ("MZ".to_string(), "Mozambique".to_string()),
        ("MM".to_string(), "Myanmar".to_string()),
        ("NA".to_string(), "Namibia".to_string()),
        ("NR".to_string(), "Nauru".to_string()),
        ("NP".to_string(), "Nepal".to_string()),
        // ("NL".to_string(), "Netherlands".to_string()),
        ("NL".to_string(), "Belgium".to_string()),
        ("AN".to_string(), "Netherlands Antilles".to_string()),
        ("NC".to_string(), "New Caledonia".to_string()),
        ("NZ".to_string(), "New Zealand".to_string()),
        ("NI".to_string(), "Nicaragua".to_string()),
        ("NE".to_string(), "Niger".to_string()),
        ("NG".to_string(), "Nigeria".to_string()),
        ("NU".to_string(), "Niue".to_string()),
        ("KP".to_string(), "North Korea".to_string()),
        ("MP".to_string(), "Northern Mariana Islands".to_string()),
        ("NO".to_string(), "Norway".to_string()),
        ("OM".to_string(), "Oman".to_string()),
        ("PK".to_string(), "Pakistan".to_string()),
        ("PW".to_string(), "Palau".to_string()),
        ("PS".to_string(), "Palestine".to_string()),
        ("PA".to_string(), "Panama".to_string()),
        ("PG".to_string(), "Papua New Guinea".to_string()),
        ("PY".to_string(), "Paraguay".to_string()),
        ("PE".to_string(), "Peru".to_string()),
        ("PH".to_string(), "Philippines".to_string()),
        ("PN".to_string(), "Pitcairn".to_string()),
        ("PL".to_string(), "Poland".to_string()),
        ("PT".to_string(), "Portugal".to_string()),
        ("PR".to_string(), "Puerto Rico".to_string()),
        ("QA".to_string(), "Qatar".to_string()),
        ("CG".to_string(), "Republic of the Congo".to_string()),
        ("RE".to_string(), "Reunion".to_string()),
        ("RO".to_string(), "Romania".to_string()),
        ("RU".to_string(), "Russia".to_string()),
        ("RW".to_string(), "Rwanda".to_string()),
        ("BL".to_string(), "Saint Barthelemy".to_string()),
        ("SH".to_string(), "Saint Helena".to_string()),
        ("KN".to_string(), "Saint Kitts and Nevis".to_string()),
        ("LC".to_string(), "Saint Lucia".to_string()),
        ("MF".to_string(), "Saint Martin".to_string()),
        ("PM".to_string(), "Saint Pierre and Miquelon".to_string()),
        (
            "VC".to_string(),
            "Saint Vincent and the Grenadines".to_string(),
        ),
        ("WS".to_string(), "Samoa".to_string()),
        ("SM".to_string(), "San Marino".to_string()),
        ("ST".to_string(), "Sao Tome and Principe".to_string()),
        ("SA".to_string(), "Saudi Arabia".to_string()),
        ("SN".to_string(), "Senegal".to_string()),
        ("RS".to_string(), "Serbia".to_string()),
        ("SC".to_string(), "Seychelles".to_string()),
        ("SL".to_string(), "Sierra Leone".to_string()),
        ("SG".to_string(), "Singapore".to_string()),
        ("SX".to_string(), "Sint Maarten".to_string()),
        ("SK".to_string(), "Slovakia".to_string()),
        ("SI".to_string(), "Slovenia".to_string()),
        ("SB".to_string(), "Solomon Islands".to_string()),
        ("SO".to_string(), "Somalia".to_string()),
        ("ZA".to_string(), "South Africa".to_string()),
        ("KR".to_string(), "South Korea".to_string()),
        ("SS".to_string(), "South Sudan".to_string()),
        ("ES".to_string(), "Spain".to_string()),
        ("LK".to_string(), "Sri Lanka".to_string()),
        ("SD".to_string(), "Sudan".to_string()),
        ("SR".to_string(), "Suriname".to_string()),
        ("SJ".to_string(), "Svalbard and Jan Mayen".to_string()),
        ("SZ".to_string(), "Swaziland".to_string()),
        ("SE".to_string(), "Sweden".to_string()),
        ("CH".to_string(), "Switzerland".to_string()),
        ("SY".to_string(), "Syria".to_string()),
        ("TW".to_string(), "Taiwan".to_string()),
        ("TJ".to_string(), "Tajikistan".to_string()),
        ("TZ".to_string(), "Tanzania".to_string()),
        ("TH".to_string(), "Thailand".to_string()),
        ("TG".to_string(), "Togo".to_string()),
        ("TK".to_string(), "Tokelau".to_string()),
        ("TO".to_string(), "Tonga".to_string()),
        ("TT".to_string(), "Trinidad and Tobago".to_string()),
        ("TN".to_string(), "Tunisia".to_string()),
        ("TR".to_string(), "Turkey".to_string()),
        ("TM".to_string(), "Turkmenistan".to_string()),
        ("TC".to_string(), "Turks and Caicos Islands".to_string()),
        ("TV".to_string(), "Tuvalu".to_string()),
        ("VI".to_string(), "U.S. Virgin Islands".to_string()),
        ("UG".to_string(), "Uganda".to_string()),
        ("UA".to_string(), "Ukraine".to_string()),
        ("AE".to_string(), "United Arab Emirates".to_string()),
        ("GB".to_string(), "United Kingdom".to_string()),
        ("US".to_string(), "United States".to_string()),
        ("UY".to_string(), "Uruguay".to_string()),
        ("UZ".to_string(), "Uzbekistan".to_string()),
        ("VU".to_string(), "Vanuatu".to_string()),
        ("VA".to_string(), "Vatican".to_string()),
        ("VE".to_string(), "Venezuela".to_string()),
        ("VN".to_string(), "Vietnam".to_string()),
        ("WF".to_string(), "Wallis and Futuna".to_string()),
        ("EH".to_string(), "Western Sahara".to_string()),
        ("YE".to_string(), "Yemen".to_string()),
        ("ZM".to_string(), "Zambia".to_string()),
        ("ZW".to_string(), "Zimbabwe".to_string()),
    ])
}
